package ris

var CMToRISMappings = map[string]string{
	"Article":               "JOUR",
	"Audiovisual":           "VIDEO",
	"Book":                  "BOOK",
	"BookChapter":           "CHAP",
	"Collection":            "CTLG",
	"Dataset":               "DATA",
	"Dissertation":          "THES",
	"Document":              "GEN",
	"Entry":                 "DICT",
	"Event":                 "GEN",
	"Figure":                "FIGURE",
	"Image":                 "FIGURE",
	"JournalArticle":        "JOUR",
	"LegalDocument":         "GEN",
	"Manuscript":            "GEN",
	"Map":                   "MAP",
	"Patent":                "PAT",
	"Performance":           "GEN",
	"PersonalCommunication": "PCOMM",
	"Post":                  "GEN",
	"ProceedingsArticle":    "CPAPER",
	"Proceedings":           "CONF",
	"Report":                "RPRT",
	"Review":                "GEN",
	"Software":              "COMP",
	"Sound":                 "SOUND",
	"Standard":              "STAND",
	"WebPage":               "WEB",
}
